language: node_js

node_js:
  - 10
  - 12
  - 14

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run build
          - npx semantic-release
